### ISSUE TITLE
panic: unable to open database file

### ISSUE THREAD

**Issue by friuns2** [HearthSim/stove#35]
hi i trying to run stove, i did steps described in https://github.com/HearthSim/stove/wiki

and i get error

```
C:\Users\Administrator\Documents\Git\src\github.com\HearthSim\stove>go run stove.go
panic: unable to open database file

goroutine 1 [running]:
panic(0xa1f960, 0xc082105900)
        C:/Go/src/runtime/panic.go:464 +0x3f4
github.com/HearthSim/stove/bnet.openDB(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/Administrator/Documents/Git/src/github.com/HearthSim/stove/bnet/db.go:19 +0x1d3
github.com/HearthSim/stove/bnet.init()
        C:/Users/Administrator/Documents/Git/src/github.com/HearthSim/stove/bnet/db.go:10 +0xe8
main.init()
        C:/Users/Administrator/Documents/Git/src/github.com/HearthSim/stove/stove.go:43 +0x47
exit status 2
```

**Comment by Mischanix** [comment]
There's a step that was missing from the wiki, `bootstrap.sh` should be run to initialize the database files.

**Comment by friuns2** [comment]
Hi thanks for reply, how i run bootstrap.sh? because i get error

C:\Users\Administrator\Documents\Git\src\github.com\HearthSim\stove>sh bootstrap.sh
: invalid optionne 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]

**Comment by jleclanche** [comment]
bootstrap.sh isn't meant to be run from Windows. Just run what it does manually.

**Comment by friuns2** [comment]
thanks got it work on linux
