### ISSUE TITLE
Presence handling

### ISSUE THREAD

**Issue by quoing** [HearthSim/stove#36]
Trying to implement presence handling, so far I have implemented (account handling - so far just adding, subscription, updates and removal of presence data)
https://github.com/quoing/stove/commit/5cc2ed980154a27ae0ed4fdc80d3105ae46aed23 
(not tested live an may still have some bugs)

I was trying to implement notifications, but I'm stuck as I either receive unhandled "notification".. or when I try to queue_packet, there is no action on client side :)

**Comment by jleclanche** [comment]
@Mischanix was talking about presence handling recently because he wants to have a "debug account" you can send cheat commands to. I'm looking forward to that.

**Comment by djkaty** [comment]
Are you still around @quoing ?

**Comment by djkaty** [comment]
Implemented, closing.
