### ISSUE TITLE
Error during bootstrap, KeyError: 'Float'

### ISSUE THREAD

**Issue by SecareLupus** [HearthSim/stove#43]
When I run bootstrap.sh, it gets into dbf_to_sqlite.py and starts creating the db. In the middle of a list of INSERT INTO ... (?, ?, ?, ?...), it fails unexpectedly. It happens consistently after it echos "INSERT INTO dbf_hero VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)".

Running Linux, if that's important

**Comment by jleclanche** [comment]
Did you try master? I think this was fixed in e42d564

**Comment by SecareLupus** [comment]
I will double check, I think I just git clone'd, which I assumed defaulted to master. I will reclone.

**Comment by SecareLupus** [comment]
So I was on master, and I thought I had cloned it more recently than the last commit, but it pulled some changes, and the problem was fixed. I did, however, have to revert the changes to scripts/dbf_to_sqlite.py from commit 8c48657 because it wouldn't compile with the encoding bits. In any case, this issue is closed, should I open a new issue about the regression in 8c4, or is there a misconfiguration on my end causing it?

**Comment by jleclanche** [comment]
What's wrong with the encoding exactly?

**Comment by jleclanche** [comment]
And are you sure you're using python 3?

**Comment by djkaty** [comment]
This is probably a version issue, the encoding keyword argument requires Python 3.

**Comment by djkaty** [comment]
I've just updated the Wiki to indicate a minimum requirement of Python 3.5

**Comment by SecareLupus** [comment]
Ah, makes sense. I have Python 3, but it looks like it's defaulting to python 2.

Thanks for the clarification.
