### ISSUE TITLE
panic when credentials are in incorrect format

### ISSUE THREAD

**Issue by farb3yonddriv3n** [HearthSim/Stove#85]
2016/09/24 21:38:49 auth.go:125: req = web_credentials:"test@hearthsim.info//0123456789abcdef0123456789abcdef" 
2016/09/24 21:38:49 session.go:159: Wrote 14 bytes
2016/09/24 21:38:49 session.go:159: Wrote 9 bytes
2016/09/24 21:38:49 server.go:130: error: Server.handleClient: length read: EOF
2016/09/24 21:38:49 session.go:172: session error: error: Server.handleClient: length read: EOF

**Comment by djkaty** [comment]
That is by design. Stove panics, you get thrown out of Hearthstone and the panic is reverted and stove continues to process existing connections and wait for new ones.
