### ISSUE TITLE
Packet 0:267 not supported

### ISSUE THREAD

**Issue by farb3yonddriv3n** [HearthSim/Stove#86]
2016/09/24 21:00:52 server.go:170: handling packet service_id:2 method_id:1 token:18 size:36  0a0c0a0170120732050a03088b020a0b0a017612061880808090030a070a017212024801
2016/09/24 21:00:52 session.go:261: Session.HandleRequest: invoking bnet.protocol.game_utilities.GameUtilities.ProcessClientRequest
2016/09/24 21:00:52 game.go:76: req = attribute:<name:"p" value:<blob_value:"\n\003\010\213\002" > > attribute:<name:"v" value:<int_value:838860800 > > attribute:<name:"r" value:<uint_value:1 > > 
2016/09/24 21:00:52 notification.go:120: Adding OnceNotified for type=GS_CL_RES
2016/09/24 21:00:52 session.go:150: Handling util packet 0:267
2016/09/24 21:00:52 session.go:169: handler does not exist for util packet 0:267
2016/09/24 21:00:52 session.go:172: session error: handler does not exist for util packet 0:267

HS client version 5.0.12574

**Comment by djkaty** [comment]
Util 267 was removed in a later patch of Hearthstone. The current master branch is designed to work with the current version of Hearthstone. Please use the latest client version.

To use 5.0.12574, please use a commit marked compatible with 5.0.12574.
